version: "3.3"
services:

  spark-master:
    image: apache/spark-py
    user: root
    ports:
      - "4040:8080"
    volumes:
      - ./input:/input:ro
      - ./src:/src
    entrypoint: /opt/spark/sbin/start-master.sh
    environment:
      - SPARK_NO_DAEMONIZE=1

  spark-worker-a:
    image: apache/spark-py
    user: root
    ports:
      - "4041:8081"
    volumes:
      - ./input:/input:ro
      - ./output/worker-a:/output
    entrypoint: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=1

  spark-worker-b:
    image: apache/spark-py
    user: root
    ports:
      - "4042:8081"
    volumes:
      - ./input:/input:ro
      - ./output/worker-b:/output
    entrypoint: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=1
